### PR TITLE
Making the error messages clearer when decryption fails.

### PR DESCRIPTION
**Pull request by diogoholanda**
This is accomplished with a StringSubstitutionException that can be recursively extended

### CODE REVIEW

**Comment by diogoholanda** [comment]
@bavardage I saw that you have a PR that addresses the same problem, but you "were not convinced" on the approach there and the PR has been opened for a while. This is an alternative. I also took a stab at increasing test coverage of some of the  classes I touched.

Most of the logic of this PR lives in StringSubstitutionException and JsonNodeStringReplacer.

Let me know what you think. If you prefer the original PR, it is fine as well.

**Comment by diogoholanda** [comment]
Tagging @bavardage and @qinfchen

**Comment by bavardage** [comment]
yeah, think this is cleaner than what I had - will do the rebase though

**Comment by bavardage** [comment]
merged as #44

**Pull request closed without merging**
