### PR TITLE
add module for ObjectMapper

### PR DESCRIPTION
**Pull request by h-korus**
Useful for non-dropwizard CLIs

Originally by @iamthomaspowell, just pulling into common repo

### CODE REVIEW

**Comment by iamthomaspowell** [comment]
Thanks!

**Comment by bavardage** [comment]
this is cool, but a nitpick - I think this should live in a separate project alongside encrypted-config-value/ and encrypted-config-value-bundle/

given this is, as you said, useful for non-dropwizard clis, probably don't wanna force people to take a transitive DW dependency to use it

**Comment by h-korus** [comment]
pulled it into an encrypted-config-value-module project

**Comment by iamthomaspowell** [comment]
Any thoughts around merging this?

**Comment by bavardage** [comment]
ooh missed the update
taking a look

**Comment by bavardage** [comment]
👍

**Pull request merged**
