### PR TITLE
make KeyWithAlgorithm json-serializable

### PR DESCRIPTION
**Pull request by bavardage**

### CODE REVIEW

**Comment by markelliot** [comment]
@jlz27 this should fix your serialization issues

**Comment by jlzhao27** [comment]
will this be release soon? also the MP client is dumb so I could make the API nicer but I still need to do manual deserialization.

**Comment by bavardage** [comment]
I'll cut a release

**Comment by jlzhao27** [comment]
great, just saw 1.5 is out, will update MP commit

**Comment by bavardage** [comment]
It’ll take a little bit for bintray to pick it up, etc. Give it 20 mins or so…

**Pull request merged**
