### PR TITLE
Factor out jackson node visitor logic so it can also be used with obj…

### PR DESCRIPTION
**Pull request by h-korus**
…ectmappers

Deleting EncryptedConfigModule and EncryptedStringDeserializer which were specific to converting encrypted String fields in favor of the type agnostic EncryptedConfigMapperUtils.

### CODE REVIEW

**Comment by h-korus** [comment]
@iamthomaspowell

**Comment by iamthomaspowell** [comment]
👍

**Comment by h-korus** [comment]
+@bavardage - pulling the json node visitor logic into the encrypted-config-value-module project

**Comment by bavardage** [comment]
👍

**Pull request merged**
