### PR TITLE
Replace Java 8 libraries with Java 7 equivalents

### PR DESCRIPTION
**Pull request by nmiyake**
We dwell in the past.

### CODE REVIEW

**Comment by nmiyake** [comment]
This makes the project compile properly using Java 7.

Unfortunately, it still won't fully run properly in Java 7 because it doesn't ship with support for AES-GCM ciphers (http://stackoverflow.com/questions/21289293/java-7-support-of-aes-gcm-in-ssl-tls, http://stackoverflow.com/questions/18396280/authenticated-encryption-in-java-7). Only real work-around for this would be to use a different crypto provider like BouncyCastle which does provide such support.

I'm willing to look into that if it's a possibility, but realize it may be beyond the scope of what we want to do to support Java 7, so will hold off on that until I hear your thoughts.

**Comment by bavardage** [comment]
oh dear, how is java 7 so lame :P

So, my current mental model (but I could be wrong here) is that it should be enough to just put bouncy castle on the classpath - then the call to getInstance https://github.com/palantir/encrypted-config-value/blob/develop/encrypted-config-value/src/main/java/com/palantir/config/crypto/algorithm/AesAlgorithm.java#L47 will use the bouncy castle provided one.

I'm also not sure where bouncy castle puts us w.r.t. crypto export control considerations.

**Comment by bavardage** [comment]
but yeah, lgtm :+1:

**Comment by markelliot** [comment]
What AES ciphers are available in Java 7?

**Comment by nmiyake** [comment]
Thanks, did a bit more research and got this working in Java 7 with ciphers.

BLUF is that I don't think this library/package needs to ship with BouncyCastle or add code to add it -- should probably be the client project/runtime's responsibility. However, might be worth adding documentation to offer this guidance for Java 7 consumers. Agree that compliance will probably need to be looped in for any project that does ship with BouncyCastle, though.

---

In order for Java 7 clients to get this to work, they need to have the BouncyCastle crypto providers and add code to add the provider to the runtime.

Gradle import: `compile 'org.bouncycastle:bcprov-jdk15on:1.54'`

Code needed to add to runtime:

```
    static {
        Security.addProvider(new BouncyCastleProvider());
    }
```

Provider can also be installed statically by modifying the JRE/JDK directly, but that's not really realistic (http://www.bouncycastle.org/wiki/display/JA1/Provider+Installation).

Documents do exist for supported ciphers in JRE 7 vs. 8, but it's a pretty dense/long read:

Supported ciphers for Java 7: http://docs.oracle.com/javase/7/docs/technotes/guides/security/SunProviders.html
Supported ciphers for Java 8: https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html

**Comment by markelliot** [comment]
Is BouncyCastle required even for asymmetric key use?

Also, would be great for you to just contribute those docs :) (this looks great!)

**Comment by nmiyake** [comment]
Nope, asymmetric keys work fine -- the `RSA/ECB/OAEPWithSHA-256AndMGF1Padding` spec that's used in `RsaAlgorithm` is present in the standard Java 7 cipher suite.

Sure, will open a PR with the docs changes for Java 7 AES usage.

**Comment by markelliot** [comment]
Sweet, we should also recommend (in these docs) that Java 7 clients have the asymmetric option for now, as well, since that requires less extra deps :)

**Pull request merged**
