### PR TITLE
Test java7

### PR DESCRIPTION
**Pull request by nmiyake**

### CODE REVIEW

**Comment by markelliot** [comment]
Instead of this, let's just fix circle.yml to use the jdk7 option instead of jdk8.

**Comment by nmiyake** [comment]
@markelliot , issue here is that I want to test 2 distinct environments:
- Java 8 (in which AES/GCM/NoPadding is included as part of the standard JCE)
- Java 7 with BouncyCastle installed as the JCE provider (because Java 7's standard JCE doesn't include AES/GCM/NoPadding, and want to have continuous tests that verify that the environment works)

Although I could set up the Circle environment to be the latter and just test that, using BouncyCastle as the JCE probably isn't the primary setup we should test. This Java environment testing is something that I've been thinking a bit about for other projects as well and am trying to figure out the best general approach.

**Comment by markelliot** [comment]
Ok, fair enough.

**Comment by markelliot** [comment]
Rebase this as well?

**Comment by nmiyake** [comment]
The concept that I explored here (wanting to run Gradle tests in different Java environments as part of a build) seemed more generic/repeatable, so I wrote a Gradle plugin to do this: https://github.palantir.build/nmiyake/gradle-docker-test-runner

If I can get publishing for that figured out, would like to try to use that to do this (I have a local copy of encrypted-config-value that uses the plugin and it seems to work). Will start a different thread for plugin feedback/thoughts.

**Comment by nmiyake** [comment]
@markelliot 

Ready for review now -- adds BouncyCastle as a test runtime-only dependency and uses `gradle-docker-test-runner` to run unit tests in JDK7 with BouncyCastle to verify that all the tests pass in that environment.

**Comment by nmiyake** [comment]
@markelliot ping -- not urgent since this just adds tests, but will test Java 7 support. This does require `gradle-docker-test-runner` since it needs to run in a JVM version that's different from the build environment (tests for Java 7 environment require Java 7 with Bouncy Castle JCE installed).

**Comment by markelliot** [comment]
Sweet, this is great, thanks!

**Pull request merged**
